name = "caveful_games/argparse"
version = "0.1.0"
description = "mpeterv/argparse for Lune"
authors = ["Peter Melnichenko", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/CavefulGames/argparse-lune"
license = "MIT"
includes = ["src", "pesde.toml", "README.md", "LICENSE"]

[target]
environment = "lune"
lib = "src/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.2.0" }
selene = { name = "pesde/selene", version = "^0.27.1" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.38.0" }
stylua = { name = "pesde/stylua", version = "^2.0.2" }
